name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm -r test
      - name: .NET build
        run: |
          dotnet build apps/api-csharp/src/ApiCSharp.csproj -c Release
          dotnet test apps/api-csharp/tests/ApiCSharp.Tests.csproj -c Release --no-build
