name: Deploy SWA
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/client/**'
      - 'apps/api-csharp/**'
      - '.github/workflows/deploy-swa.yml'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet build apps/api-csharp/src/ApiCSharp.csproj -c Release
      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'apps/client'
          api_location: 'apps/api-csharp/src'
          output_location: 'dist'
